Návrh opravy Vyfakturuj SDK s ohledem na SimpleShop API
redbitcz/simpleshop-api-php-sdk pull request #1
Opened 2020-08-24 13:58 UTC by BadKoldrysh

2020-08-24 14:05 UTC, jakubboucek commented on examples/00-config.php
> +define('SIMPLESHOP_API_KEY', 'owOmRdjNrpvJZWY1vdaunaQezwEe1K4kG9labzyM');    // API klíč, který najdete v Nastavení -> API
Tohle MUSÍ být prázdné. Každý uživatel si musí vygenerovat vlastní token.

Prosím @BadKoldrysh :
- [ ] Odstraň tyto hodnoty z repozitáře
- [ ] Zneplatni token v systému

2020-08-24 14:06 UTC, jakubboucek commented on examples/00-config.php
> +define('SIMPLESHOP_API_KEY', 'owOmRdjNrpvJZWY1vdaunaQezwEe1K4kG9labzyM');    // API klíč, který najdete v Nastavení -> API
Tohle MUSÍ být prázdné. Každý uživatel si musí vygenerovat vlastní token. Viz příklad na VF: https://github.com/redbitcz/vyfakturuj-api-php/blob/c11587a58e12eb1baf12991f258f45ba392459f0/examples/00-config.php#L13-L14

Prosím @BadKoldrysh :
- [ ] Odstraň tyto hodnoty z repozitáře
- [ ] Zneplatni token v systému

2020-08-24 14:08 UTC, jakubboucek requested changes
Doplnil jsem jeden postřeh, a prosím dohledni na doplnění řádků v EOL.

2020-08-25 07:08 UTC, BadKoldrysh commented
> Doplnil jsem jeden postřeh, a prosím dohledni na doplnění řádků v EOL.
Myslíš, když chybí EOL na konci souborů?

2020-08-25 07:09 UTC, BadKoldrysh commented
@jakubboucek Myslíš, když na konci souborů chybí EOL?

2020-08-25 07:18 UTC, Dosty85 reviewed
Prosím projít a všude změnit Vyfakturuj -> SimpleShop

2020-08-25 07:18 UTC, Dosty85 commented on composer.json
> +  "name": "vyfakturuj/simpleshop-api-php",
Neměli bychom změnit namespace?? Mít místo Vyfakturuj -> SimpleShop?

2020-08-25 07:18 UTC, Dosty85 commented on examples/README.md
> +# Příklady použití [PHP knihovny Vyfakturuj API](https://github.com/redbitcz/vyfakturuj-api-php)
Vyfakturuj -> SimpleShop

2020-08-25 07:18 UTC, Dosty85 commented on examples/README.md
> +které najdete v [nastavení API ve Vyfakturuj](https://app.vyfakturuj.cz/nastaveni/api/).
Vyfakturuj -> SimpleShop

2020-08-25 07:18 UTC, Dosty85 commented on examples/assets/example-layout.php
> + * @author Ing. Martin Dostál
Autora změn na Redbit s.r.o.

2020-08-25 10:22 UTC, jakubboucek commented
> @jakubboucek Myslíš, když na konci souborů chybí EOL?

Ano, přidat na konec všech souborů (kde to dává smysl) konec řádku.

2020-09-08 08:38 UTC, BadKoldrysh commented on examples/README.md
> +které najdete v [nastavení API ve Vyfakturuj](https://app.vyfakturuj.cz/nastaveni/api/).
done

2020-09-08 08:38 UTC, BadKoldrysh commented on examples/README.md
> +# Příklady použití [PHP knihovny Vyfakturuj API](https://github.com/redbitcz/vyfakturuj-api-php)
done

2020-09-08 08:38 UTC, BadKoldrysh commented on composer.json
> +  "name": "vyfakturuj/simpleshop-api-php",
done

2020-09-08 08:39 UTC, BadKoldrysh commented on examples/00-config.php
> +define('SIMPLESHOP_API_KEY', 'owOmRdjNrpvJZWY1vdaunaQezwEe1K4kG9labzyM');    // API klíč, který najdete v Nastavení -> API
done

2021-05-19 09:19 UTC, BadKoldrysh commented
Větev je zastaralá. Uzavírám.

2021-05-19 09:19 UTC, closed without merging